### ISSUE TITLE
dephell project test not working for dephell

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#127]
Maybe I'm missing something here, but I've started playing with the dephell source code so I can maybe start work on an issue.  Rather than using Poetry to create a venv and run pytest myself (as I was tempted to do), I figured I should use the dephell test functionality.  In the pyproject.toml, the pytest env shows the example command `dephell project test --env pytest`.  When I run this, 12 tests fail.  I haven't dug into the tests yet, but looks like they require a .git folder.

Is this expected behavior?  Seems strange that the test command doesn't work for testing dephell itself.

**Comment by orsinium** [comment]
:thinking:
I used it before. Hm, that strange. Luckily, these tests marked as skip on ci. We can modify skip rule a little bit to skip them if there is no git folder :)

**Comment by eli-schwartz** [comment]
I have just run `pytest` in a chroot containing the minimal dependencies to do distro packaging; I get only three test failures, those being all the tests in test_git_git. The failures are due to:
- not having the git program installed
- not being able to find the .git directory in the extracted PyPI sources (of course).

At the moment, I can get it to work using `pytest -k 'not test_git_git'` to skip those three tests.

**Comment by dbanty** [comment]
So the Git tests are 3 out of the 12 failing tests for me.  I'm attaching a file that shows the remaining failures.

[failures.txt](https://github.com/dephell/dephell/files/3243324/failures.txt)
