### ISSUE TITLE
Dephell has too many dependencies

### ISSUE THREAD

**Issue by KOLANICH** [dephell/dephell#347]
## Short description
Do I really need
<details open="true">
<summary>at least 19 direct deps not claimed to be in dephell ecosystem</summary>

```ini
aiohttp = "*"
appdirs = "*"
bowler = "*"
cerberus = ">=1.3"
docker = "*"
dockerpty = "*"
fissix = {allows-prereleases = true, version = "*"}
flatdict = "*"
html5lib = "*"
jinja2 = "*"
m2r = "*"
packaging = "*"
pip = ">=18.0"
pygments = "*"
requests = "*"
"ruamel.yaml" = "*"
tabulate = "*"
tomlkit = "*"
yaspin = "*"
```
</details>

in order to just convert from poetry to setuptools?

Also in https://github.com/hgrecco/pint/pull/755#issuecomment-567574971 you have claimed

> Most of dependencies of dephell are packages from dephell's own ecosystem.

but
<details>
<summary>there are 12 direct deps of this package claimed to be in dephell ecossystem (&lt; 19 not claimed to be in the ecosystem) </summary>

```ini
# dephell ecosystem
dephell-archive = ">=0.1.5"
dephell-argparse = ">=0.1.1"
dephell-discover = ">=0.2.6"
dephell-licenses = ">=0.1.6"
dephell-links = ">=0.1.4"
dephell-markers = ">=1.0.0"
dephell-pythons = ">=0.1.11"
dephell-setuptools = ">=0.2.1"
dephell-shells = ">=0.1.3"
dephell-specifier = ">=0.1.7"
dephell-venvs = ">=0.1.16"
dephell-versioning = "*"
```
</details>

and I also don't understand why I should have to have them all.

>The recommended way to install dephell is curl -L dephell.org/install | python3 that installs DepHell into its own isolation that keeps the global environment clean.

IMHO it is a wrong way to do the things. 
1. The practice of pyping external scripts to interpreters is also inherently harmful. If one uses scripts for installation, they must be:
    1. downloaded
    2. fully read and understood
    3. fixed, if there are some minor issues or discarded completely if there are major ones
   4. only then run.

2. There is no benefits in the isolation provided by venvs but only harm. They decouple dependencies, is harmful because it duplicates the deps and prevents them from being upgraded. Venvs also cannot provide security benefits. You still have to run untrusted code. Venvs don't prevent it from reading sensitive data from your `~` and sending it to adversary. Even executing in hw-virtualized VM cannot give you any guarantee - there are no ways to both reliably sandbox software written in Turing-complete languages and keep it anyhow useful (a trivial and absolutely reliable way to sandbox any software is not to execute it at all, a not so trivial is to execute on an ideal CPU without any bugs, side-channels, multithreading, io and sensitive data present anywhere).

<details>
<summary>Some offtop</summary>

BTW, how have you come to that PR? Do you use any social media tracking system?
</details>

**Comment by orsinium** [comment]
As I said in the PR, the recommend way to install dephell installs it into the jail. All these packages (except flatdict) are required for some dephell commands. Dephell is a tool that I just install and everything works, I don't want to see "if you want to do it, install these extras" on every command.

Another option is vendorization. That's what all package managers in Python does, right? Dephell can be easily vendorized by `dephell vendor` commands. However, it has tradeoffs:
1. The same class from the vendored package and from the real package have different ids. So, all isinstance checks will be broken.
2. Downstrdams. You can't use vendorization for debian packages, that's the rules.
3. Reusage. Every package will be installed twice, as a real package and as vendored one. So, you'll end up with node_modules-like huge directory.
4. Import time. Everything is imported twice, and Python can't cache it anymore.
5. More traffic. Yep, everything will be downloaded twice.
6. You lost control of updates. Dephell decides which versions of everything it uses.

And for what? Your concern is you want only convert one particular format to another one. Well, Dephell is a tool to manage dependencies, not a library. Do you have Poetry in your list of dependencies? No, because you need it before installing dependencies. Dephell is the same. Dephell is a tool that can totally replace poetry and everything else (except twine yet), let's be honest here.

However, I invest a lot to make dephell useful as a library as well. You see these packages in the ecosystem. Every package has maximum 3 dependencies, type annotated, and supports windows. This is the place where dephell really cares about dependencies and size. However, converters can't be decoupled from the dephell because they are heavily connected with models, resolver, and repositories, and that is 80% of the tool itself.

So, let's talk what you can do:
1. Install dephell as a tool, give it a try. Put in your project the dephell config and enjoy all-in-one solution that not just converter.
2. Make a small ad-hoc Python script that does what you want. No dependencies, fast, takes less time to make than you spent on making that issue. Thanks, Python, for making coding really fast.

Also, that should be said, I keep fighting for as less dependencies as possible. A lot of deps already optional. The next release will have no fastdict just because I can re-implement it. But it's a difficult fight, and I have no time and motivation to re-implement requests, attts, and everything else that already perfectly done by smart people, and I can focus on the important things that make dephell cool.

**Comment by KOLANICH** [comment]
>All these packages (except flatdict) are required for some dephell commands.

For some. Not for all, right? From de-hell I only need only conversion between metadata formats, I don't need anything else. Why do I have to have dependencies for everything else? Anyy additional dependency is an additional risk. Any dependency installed from pipa is the risk multiplied because noone reads the code in pypa packages.

>Dephell is a tool that I just install and everything works, I don't want to see "if you want to do it, install these extras" on every command.

You can add an extra `all`.

>Another option is vendorization. That's what all package managers in Python does, right? 

Right. They use this because package manager is a critical software, if it is broken there is no easy way to restore it. Under easy way I mean using the package manager itself.

IMHO vendoring should be avoided as much as it makes sense to avoid it.

>Well, Dephell is a tool to manage dependencies, not a library. Do you have Poetry in your list of dependencies? No, because you need it before installing dependencies. Dephell is the same. Dephell is a tool that can totally replace poetry and everything else (except twine yet), let's be honest here.

In fact I need the tool that
* will check the python build systems installed
* if the system is not not installed, the tool should convert the metadata in the missing system format into the format of the chosen present system (I prefer setuptools) and use it without dumping the manifest on the media.

In fact the need in the tools like this one is a result of bad decisions made by PSF. In fact I'd liked if there was a one standardized metadata format and all the tools have to use it.

>However, I invest a lot to make dephell useful as a library as well. You see these packages in the ecosystem. Every package has maximum 3 dependencies, type annotated, and supports windows. This is the place where dephell really cares about dependencies and size.
>Also, that should be said, I keep fighting for as less dependencies as possible.

Thank you.
>I have no time and motivation to re-implement requests, attts, and everything else that already perfectly done by smart people

I don't ask you to reimplement the deps. I ask you to make as much optional as it is possible. For example I use docker for CI, but using docker for package managegent is IMHO a big overkill. So I currently have no plans to use Docker-related features. So I probably don't need this feature dependencies.

>However, converters can't be decoupled from the dephell because they are heavily connected with models, resolver, and repositories, and that is 80% of the tool itself.

Yeah. In my packages I have faced the similar issues.  I solve them with dependency injection. A backend defines an entry point. Frontend discovers backends entry points and calls them, providing references to own classes. Backends parts needing these classes are defined within a function to which the entry point points. The function creates a class for a backend and returns. Then the middleware receives this class and creates the actual object.

Here are some examples: https://gitlab.com/File2Package.py/File2Package.py https://gitlab.com/File2Package.py/File2Package.backend.dpkg .

>Make a small ad-hoc Python script that does what you want. No dependencies, fast, takes less time to make than you spent on making that issue. Thanks, Python, for making coding really fast.

It's a wrong approach. If I had written the own tool I would have to
* maintain and develop it myself -t he thing I have no plans for;
* compete to dephell, so instead of 1 great tool there would be 2 not so great.

These all are problems for nothing.

**Comment by KOLANICH** [comment]
Thanks.
