### ISSUE TITLE
[BUG] Cannot use "version.py" with "dephell project bump"

### ISSUE THREAD

**Issue by jaklan** [dephell/dephell#388]
## Short description

When using:
```
dephell project bump --from=PACKAGE_NAME/version.py minor
```
with `version.py` looking like this:
```
__version__ = "0.3.1"
```

I get such an error:
```
WARNING cannot find config file
WARNING cannot get version from `from` file
ERROR cannot find old project version
```

## Expected behaviour

Bump the version.

## Steps to reproduce

1. Create `version.py` file, like the above one, in your project.
2. Run `dephell project bump --from=PACKAGE_NAME/version.py minor`

# Versions

`"version": "0.8.1"`

**Comment by orsinium** [comment]
--from specifies dependency file, not a random python file. Please, try without this flag, just `dephell project bump`

**Comment by jaklan** [comment]
@orsinium that doesn't resolve the problem with using a file, which is not specified here:
https://github.com/dephell/dephell/blob/e95b34abad8fa27831ba8c33e88c77de52b2688f/dephell/commands/project_bump.py#L19

Btw, what do you mean by "dependency file"?

**Comment by orsinium** [comment]
setup.py is your dependency file, I guess.

**Comment by jaklan** [comment]
@orsinium Ok, now I see you what is that for. Anyway, the problem with `version.py` is still valid - and imho adding it to the list would be enough for now, you would get all most popular variants then. For the future - some option, e.g. `--to`, would be perfect.

Btw - that would be also great to look into e.g. poetry implementation of `poetry version` to be able to bump version in pyproject.toml as well.

**Comment by orsinium** [comment]
1. `--to` used for output format in convertion (for example, lock file), and `bump` takes it into account as well.
2. There is no need to specify path to python with version. Let's make it smart, add one more name isn't hard. Also, I recommend to keep version in `__init__.py` since there are a lot of tools that will look only here. 
1. You can specify `pyproject.toml` as `--from`, and dephell will bump it too. Dephell's `bump` command is definitely the smartest one.

Please, take a look at the documentation, start from "Getting started". It will save you a lot of time, and tell about a lot of cool features around.

**Comment by jaklan** [comment]
@orsinium  
1. I see, that was only a sample name. But what do you mean by 
> takes it into account as well 

? As I can see, it's an invalid `bump` option.
2. Agree, and that's what I'm normally doing, but I have some legacy code with that approach (it's even mention in [PyPA User Guide](https://packaging.python.org/guides/single-sourcing-package-version/) btw):
> Set the value to a __version__ global variable in a dedicated module in your project (e.g. version.py), then have setup.py read and exec the value into a variable.
so that's why I wanted to handle that.
3. Oh, that's pretty cool, I missed that one.

Yeah, I read both general and `bump` docs, just didn't focus on the last step of command description, mea culpa ;)
