### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#49]
We can use docker instead of venv, it's quite simple. See [pydockenv](https://github.com/se7entyse7en/pydockenv) for example. Unfortunately, this lib doesn't provide any API, so let's reimplement it.

**Comment by lorddaedra** [comment]
With Docker we usually use several images in matrioshka style: 

1. Official Python image (https://hub.docker.com/_/python) [based on Alpine in our case, alternatives: Debian-based Python image or use other base official OS images like Ubuntu]
2. Custom base image with some tools and popular packages like Pillow and with support for PostgreSQL, zstd etc. (if we have 100 python-based microservices, we save time and update some popular packages once in base image) [this image based on 1.]
3. project-level python image with all other Python packages [this image based on 2.]

Currently we use pip to do that. 

a.) Our main interest here - find way to somehow add support for package sha hashes (for security reasons). 

b.) Good if it will be without any virtual envs (because of we use containers for all, in DEV too, PyCharm integrate with containers). 

c.) Also we would like to have simple way to update all required python packages on 3 level with all their deps BUT without packages specified on level 2 (base) and their deps [because of 

    1. for this task much better do this on level 2; 
    2. also updating packages of level 2 on level 3 may be not possible because of system library headers deps (which have been installed and removed during base image build)
].

**Comment by orsinium** [comment]
Thank you for your feedback. I think, DepHell shouldn't force any structure for project. Good solution here is allow users to specify custom image in config (and sha for security checks). It should cover your cases too.
